### ISSUE TITLE
Get Python example to work

### ISSUE THREAD

**Issue by frankgerhardt** [flok99/clewarecontrol#3]
Following the instructions in readme-python.txt I was able to build these two files on Debian 8.1:
```
-rwxr-xr-x 1 user user 339904 Sep 23 19:19 _cleware.so
-rw-r--r-- 1 user user  14808 Sep 23 19:21 cleware.pyc
```
Then I looked what my Python path is
```
~$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.path
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7']
```
I copied the two files into the first dir, /usr/lib/python2.7

In a python console I tried the first import statement from example.py and I get this error:
```python
>>> import cleware
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/cleware.py", line 28, in <module>
    _cleware = swig_import_helper()
  File "/usr/lib/python2.7/cleware.py", line 24, in swig_import_helper
    _mod = imp.load_module('_cleware', fp, pathname, description)
ImportError: /usr/lib/python2.7/_cleware.so: undefined symbol: hid_send_feature_report
```
What is missing here?

To avoid permission problem, I run the Python code as root. (The udev rule is working for the clewarecontrol executable so that a normal user can use it)

**Comment by flok99** [comment]
Hi looks like it cannot find the hidapi library.
Did you install it?

On Thu, Sep 24, 2015 at 11:22 PM, frankgerhardt <notifications@github.com>
wrote:

> Following the instructions in readme-python.txt I was able to build these
> two files on Debian 8.1:
>
> -rwxr-xr-x 1 user user 339904 Sep 23 19:19 _cleware.so
> -rw-r--r-- 1 user user  14808 Sep 23 19:21 cleware.pyc
>
> Then I looked what my Python path is
>
> ~$ python
> Python 2.7.9 (default, Mar  1 2015, 12:57:24)
> [GCC 4.9.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import sys
> >>> print sys.path
> ['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7']
>
> I copied the two files into the first dir, /usr/lib/python2.7
>
> In a python console I tried the first import statement from example.py and
> I get this error:
>
> >>> import cleware
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python2.7/cleware.py", line 28, in <module>
>     _cleware = swig_import_helper()
>   File "/usr/lib/python2.7/cleware.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_cleware', fp, pathname, description)ImportError: /usr/lib/python2.7/_cleware.so: undefined symbol: hid_send_feature_report
>
> What is missing here?
>
> To avoid permission problem, I run the Python code as root. (The udev rule
> is working for the clewarecontrol executable so that a normal user can use
> it)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/clewarecontrol/issues/3>.
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by frankgerhardt** [comment]
hidapi is installed, it's Debian 8.1
```
~$ dpkg --get-selections | grep hidapi
libhidapi-dev:amd64				install
libhidapi-hidraw0:amd64				install
libhidapi-libusb0:amd64				install
```

**Comment by flok99** [comment]
what happens when you do:

LD_PRELOAD=/path/to/so-file python myscript.py


On Thu, Oct 1, 2015 at 8:14 PM, frankgerhardt <notifications@github.com>
wrote:

> hidapi is installed, it's Debian 8.1
>
> ~$ dpkg --get-selections | grep hidapi
> libhidapi-dev:amd64             install
> libhidapi-hidraw0:amd64             install
> libhidapi-libusb0:amd64             install
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/clewarecontrol/issues/3#issuecomment-144834855>
> .
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by briconaut** [comment]
Hi,
I have the same problem. The LD_PRELOAD=... fixes the problem. But how can we get this to work without this workaround?

**Comment by flok99** [comment]
Try moving the lib-files to a directory that is in the ld-search path.
Or add its path to /etc/ld.so.conf
Don't forget to run ldconfig afterwards.

On Wed, Dec 2, 2015 at 11:13 AM, briconaut <notifications@github.com> wrote:

> Hi,
> I have the same problem. The LD_PRELOAD=... fixes the problem. But how can
> we get this to work without this workaround?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flok99/clewarecontrol/issues/3#issuecomment-161247174>
> .
>



-- 
www.vanheusden.com  www.slimwinnen.nl | www.smartwinning.info

**Comment by briconaut** [comment]
I've set my LD_LIBRARY_PATH to the location of the library, but it still won't work.
But I think the problem is not in clewarecontrol. It looks more like a problem either with my local ld-configuration or the build of the libhidapi... libraries.

**Comment by zoff99** [comment]
it runs on ubuntu see:
#6

**Comment by zoff99** [comment]
#10
